# -*- coding: utf-8 -*-
"""Projeto_Redes_Complexas_Proteina_Teste_1A3N_e_Proteina_Alvo_6B1T.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbtIksW4IHq9IWIn8Kf-Rj6eyv52eUT9

# Projeto de Redes Complexas — 1A3N e 6B1T

## Detecção de domínios funcionais em proteínas por redes complexas

Este notebook reúne, em um único arquivo, a execução completa do projeto:

1. **Proteína de teste:** 1A3N, usada para validar o pipeline em uma proteína menor e com múltiplas cadeias.
2. **Proteína-alvo:** 6B1T, estrutura principal indicada no projeto.

O notebook foi organizado para produzir automaticamente as figuras e tabelas que podem ser utilizadas no relatório final:

- parâmetros da modelagem;
- resíduos carregados;
- métricas da rede;
- distribuição de graus;
- centralidades;
- comunidades Louvain;
- tabelas de validação;
- heatmaps de correspondência;
- visualizações 3D;
- arquivos `.csv`, `.png`, `.html` e `.txt` para o relatório.

# 1. Instalação das bibliotecas
"""

import sys
import subprocess

pacotes = [
    "biopython",
    "networkx",
    "python-louvain",
    "plotly",
    "pandas",
    "matplotlib",
    "scipy",
    "scikit-learn",
    "tqdm",
    "kaleido"
]

print("Instalando/verificando bibliotecas...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q"] + pacotes)
print("Bibliotecas instaladas/verificadas com sucesso.")

"""# 2. Importação das bibliotecas"""

import os
import glob
import shutil
import urllib.request
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import plotly.graph_objects as go

from Bio.PDB import PDBParser
from scipy.spatial import cKDTree
from community import community_louvain
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score, homogeneity_score, completeness_score
from tqdm.auto import tqdm

warnings.filterwarnings("ignore")

plt.rcParams["figure.dpi"] = 120
plt.rcParams["savefig.dpi"] = 200

"""# 3. Parâmetros gerais do projeto

Os parâmetros abaixo são utilizados tanto na proteína de teste 1A3N quanto na proteína-alvo 6B1T, sempre que aplicável.
"""

# ============================================================
# Parâmetros gerais
# ============================================================
DISTANCE_THRESHOLD = 8.0
LOUVAIN_RESOLUTION_TESTE = 1.0
LOUVAIN_RESOLUTION_6B1T = 1.0
RANDOM_STATE = 42

# Centralidades
CALCULAR_CLOSENESS = True
CALCULAR_EIGENVECTOR = True
CALCULAR_PAGERANK = True
CALCULAR_BETWEENNESS_EXATA = False
BETWEENNESS_K_TESTE = None       # None = exata para 1A3N
BETWEENNESS_K_6B1T = 300         # aproximada para 6B1T

# Diretórios
BASE_OUTPUT_DIR = "resultados"
DIR_TESTE = os.path.join(BASE_OUTPUT_DIR, "1A3N")
DIR_6B1T = os.path.join(BASE_OUTPUT_DIR, "6B1T")

os.makedirs(DIR_TESTE, exist_ok=True)
os.makedirs(DIR_6B1T, exist_ok=True)

print("="*70)
print("CONFIGURAÇÃO GERAL DO PROJETO")
print("="*70)
print(f"Limiar de distância Cα-Cα: {DISTANCE_THRESHOLD} Å")
print(f"Resolution Louvain 1A3N  : {LOUVAIN_RESOLUTION_TESTE}")
print(f"Resolution Louvain 6B1T  : {LOUVAIN_RESOLUTION_6B1T}")
print(f"Betweenness 1A3N         : {'exata' if BETWEENNESS_K_TESTE is None else 'aproximada'}")
print(f"Betweenness 6B1T         : aproximada, k={BETWEENNESS_K_6B1T}")
print(f"Saída geral              : {BASE_OUTPUT_DIR}")
print("="*70)

"""# 4. Funções auxiliares

As funções abaixo são usadas nas duas proteínas. Isso evita duplicação de código e garante que a proteína de teste e a proteína-alvo sejam analisadas pelo mesmo pipeline.
"""

def limpar_diretorio(path):
    os.makedirs(path, exist_ok=True)
    for item in os.listdir(path):
        full = os.path.join(path, item)
        if os.path.isfile(full) or os.path.islink(full):
            os.remove(full)
        elif os.path.isdir(full):
            shutil.rmtree(full)


def baixar_pdb(pdb_id, output_dir):
    """Baixa um arquivo PDB simples diretamente do RCSB."""
    os.makedirs(output_dir, exist_ok=True)
    url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    path = os.path.join(output_dir, f"{pdb_id}.pdb")
    print(f"Baixando {pdb_id} do RCSB...")
    urllib.request.urlretrieve(url, path)
    print("Arquivo salvo em:", path)
    return path


def carregar_residuos_ca(pdb_files, pdb_id, max_residues=None):
    """Carrega resíduos usando o átomo Cα como representante espacial."""
    parser = PDBParser(QUIET=True)
    residuos = []
    node_id = 0

    if isinstance(pdb_files, str):
        pdb_files = [pdb_files]

    for pdb_file in pdb_files:
        print("Lendo:", pdb_file)
        estrutura = parser.get_structure(pdb_id, pdb_file)

        for modelo in estrutura:
            for cadeia in modelo:
                for residuo in cadeia:
                    if "CA" not in residuo:
                        continue

                    atom_ca = residuo["CA"]
                    res_id = residuo.get_id()

                    residuos.append({
                        "node_id": node_id,
                        "pdb_id": pdb_id,
                        "source_file": os.path.basename(pdb_file),
                        "model_id": modelo.id,
                        "chain_id": str(cadeia.id),
                        "residue_name": residuo.get_resname(),
                        "residue_number": int(res_id[1]),
                        "insertion_code": res_id[2].strip() if res_id[2].strip() else "",
                        "x": float(atom_ca.coord[0]),
                        "y": float(atom_ca.coord[1]),
                        "z": float(atom_ca.coord[2])
                    })

                    node_id += 1
                    if max_residues is not None and node_id >= max_residues:
                        return pd.DataFrame(residuos)

    return pd.DataFrame(residuos)


def construir_rede_por_distancia(df_residuos, distance_threshold=8.0):
    """Constrói grafo não direcionado usando KDTree para pares Cα-Cα dentro do limiar."""
    coords = df_residuos[["x", "y", "z"]].values
    tree = cKDTree(coords)
    pares = sorted(tree.query_pairs(r=distance_threshold))

    G = nx.Graph()

    for _, row in df_residuos.iterrows():
        G.add_node(
            int(row["node_id"]),
            pdb_id=row["pdb_id"],
            source_file=row["source_file"],
            chain_id=row["chain_id"],
            residue_name=row["residue_name"],
            residue_number=int(row["residue_number"]),
            insertion_code=row["insertion_code"],
            x=float(row["x"]),
            y=float(row["y"]),
            z=float(row["z"])
        )

    for i, j in pares:
        dist = float(np.linalg.norm(coords[i] - coords[j]))
        G.add_edge(int(i), int(j), distance=dist, weight=1.0)

    return G


def metricas_rede(G):
    graus = dict(G.degree())
    componentes = list(nx.connected_components(G))
    maior_comp = max(componentes, key=len) if componentes else []

    return pd.DataFrame({
        "Métrica": [
            "Nós", "Arestas", "Densidade", "Grau médio", "Grau máximo",
            "Coeficiente de agrupamento médio", "Componentes conectados", "Maior componente"
        ],
        "Valor": [
            G.number_of_nodes(),
            G.number_of_edges(),
            nx.density(G),
            np.mean(list(graus.values())) if graus else 0,
            max(graus.values()) if graus else 0,
            nx.average_clustering(G) if G.number_of_nodes() > 0 else 0,
            len(componentes),
            len(maior_comp)
        ]
    })


def salvar_metricas_rede(G, output_dir, prefix):
    df = metricas_rede(G)
    df.to_csv(os.path.join(output_dir, f"{prefix}_metricas_rede.csv"), index=False, encoding="utf-8-sig")
    display(df)
    return df


def plot_distribuicao_graus(G, output_dir, prefix, titulo):
    graus = np.array([d for _, d in G.degree()])
    df_graus = pd.DataFrame({"grau": graus})

    freq = df_graus["grau"].value_counts().sort_index().reset_index()
    freq.columns = ["grau", "frequencia"]

    freq.to_csv(
        os.path.join(output_dir, f"{prefix}_distribuicao_graus.csv"),
        index=False,
        encoding="utf-8-sig"
    )

    plt.figure(figsize=(8, 5))
    plt.hist(graus, bins=30, edgecolor="black", alpha=0.8)
    plt.axvline(graus.mean(), linestyle="--", label=f"média = {graus.mean():.2f}")
    plt.title(titulo)
    plt.xlabel("Grau")
    plt.ylabel("Número de resíduos")
    plt.legend()
    plt.tight_layout()
    path_hist = os.path.join(output_dir, f"{prefix}_histograma_graus.png")
    plt.savefig(path_hist, dpi=300)
    plt.show()

    freq_log = freq[freq["frequencia"] > 0]

    plt.figure(figsize=(7, 5))
    plt.scatter(freq_log["grau"], freq_log["frequencia"])
    plt.xscale("log")
    plt.yscale("log")
    plt.title(f"{titulo} — escala log-log")
    plt.xlabel("Grau k (log)")
    plt.ylabel("Frequência P(k) (log)")
    plt.grid(True, which="both", alpha=0.3)
    plt.tight_layout()
    path_log = os.path.join(output_dir, f"{prefix}_graus_loglog.png")
    plt.savefig(path_log, dpi=300)
    plt.show()

    return freq, path_hist, path_log


def calcular_centralidades(G, output_dir, prefix, betweenness_k=None):
    print("Calculando centralidade de grau...")
    degree = nx.degree_centrality(G)

    closeness = {}
    eigenvector = {}
    pagerank = {}
    betweenness = {}

    if CALCULAR_CLOSENESS:
        print("Calculando Closeness...")
        closeness = nx.closeness_centrality(G)

    if CALCULAR_EIGENVECTOR:
        print("Calculando Eigenvector...")
        try:
            eigenvector = nx.eigenvector_centrality(G, max_iter=1000, tol=1e-06)
        except Exception as e:
            print("Eigenvector não convergiu:", e)
            eigenvector = {n: np.nan for n in G.nodes()}

    if CALCULAR_PAGERANK:
        print("Calculando PageRank...")
        pagerank = nx.pagerank(G, alpha=0.85, max_iter=200, weight="weight")

    print("Calculando Betweenness...")
    if betweenness_k is None:
        betweenness = nx.betweenness_centrality(G, normalized=True, weight=None)
    else:
        betweenness = nx.betweenness_centrality(
            G,
            k=betweenness_k,
            normalized=True,
            seed=RANDOM_STATE,
            weight=None
        )

    dados = []
    for n in G.nodes():
        attrs = G.nodes[n]
        dados.append({
            "node_id": n,
            "chain_id": attrs.get("chain_id"),
            "residue_name": attrs.get("residue_name"),
            "residue_number": attrs.get("residue_number"),
            "grau": G.degree(n),
            "degree_centrality": degree.get(n, np.nan),
            "closeness": closeness.get(n, np.nan),
            "eigenvector": eigenvector.get(n, np.nan),
            "pagerank": pagerank.get(n, np.nan),
            "betweenness": betweenness.get(n, np.nan),
            "x": attrs.get("x"),
            "y": attrs.get("y"),
            "z": attrs.get("z"),
        })

    df_cent = pd.DataFrame(dados)

    df_cent.to_csv(
        os.path.join(output_dir, f"{prefix}_centralidades.csv"),
        index=False,
        encoding="utf-8-sig"
    )

    for col in ["grau", "degree_centrality", "closeness", "eigenvector", "pagerank", "betweenness"]:
        if col in df_cent.columns:
            top = df_cent.sort_values(col, ascending=False).head(20)

            top.to_csv(
                os.path.join(output_dir, f"{prefix}_top20_{col}.csv"),
                index=False,
                encoding="utf-8-sig"
            )

            print(f"\nTop 20 - {col}")
            display(top[["node_id", "chain_id", "residue_name", "residue_number", col]].round(6))

    return df_cent


def plot_histogramas_centralidades(df_cent, output_dir, prefix, titulo):
    cols = [
        ("degree_centrality", "Degree"),
        ("closeness", "Closeness"),
        ("eigenvector", "Eigenvector"),
        ("pagerank", "PageRank"),
        ("betweenness", "Betweenness")
    ]

    fig, axes = plt.subplots(3, 2, figsize=(12, 12))
    axes = axes.ravel()

    for ax, (col, label) in zip(axes, cols):
        if col in df_cent.columns:
            valores = df_cent[col].dropna()
            ax.hist(valores, bins=30, edgecolor="black", alpha=0.8)
            ax.set_title(label)
            ax.set_xlabel("Valor")
            ax.set_ylabel("Nº de resíduos")
            ax.grid(alpha=0.2)

    axes[-1].axis("off")
    fig.suptitle(titulo, fontsize=14)
    plt.tight_layout()
    path = os.path.join(output_dir, f"{prefix}_histogramas_centralidades.png")
    plt.savefig(path, dpi=300)
    plt.show()

    return path


def detectar_comunidades_louvain(G, output_dir, prefix, resolution=1.0):
    print("Aplicando Louvain...")

    # Correção principal:
    # o python-louvain exige que o parâmetro weight seja uma string.
    # Portanto, usamos o atributo "weight" das arestas.
    for u, v, data in G.edges(data=True):
        data["weight"] = float(data.get("weight", 1.0))

    partition = community_louvain.best_partition(
        G,
        weight="weight",
        resolution=resolution,
        random_state=RANDOM_STATE
    )

    nx.set_node_attributes(G, partition, "community")

    modularidade = community_louvain.modularity(
        partition,
        G,
        weight="weight"
    )

    num_comunidades = len(set(partition.values()))

    df_com = pd.DataFrame({
        "node_id": list(partition.keys()),
        "community": list(partition.values())
    })

    for attr in ["chain_id", "residue_name", "residue_number", "source_file", "x", "y", "z"]:
        df_com[attr] = df_com["node_id"].map(lambda n: G.nodes[n].get(attr))

    df_com.to_csv(
        os.path.join(output_dir, f"{prefix}_comunidades_louvain.csv"),
        index=False,
        encoding="utf-8-sig"
    )

    resumo = (
        df_com.groupby("community")
        .size()
        .reset_index(name="quantidade_residuos")
        .sort_values("quantidade_residuos", ascending=False)
    )

    resumo.to_csv(
        os.path.join(output_dir, f"{prefix}_resumo_comunidades.csv"),
        index=False,
        encoding="utf-8-sig"
    )

    print(f"Número de comunidades: {num_comunidades}")
    print(f"Modularidade: {modularidade:.4f}")

    display(resumo)

    return partition, modularidade, num_comunidades, df_com, resumo


def plot_heatmap_crosstab(tabela, output_dir, filename, titulo, xlabel, ylabel):
    plt.figure(figsize=(max(8, 0.45 * tabela.shape[1] + 4), max(5, 0.35 * tabela.shape[0] + 3)))
    plt.imshow(tabela.values, aspect="auto")
    plt.colorbar(label="Quantidade de resíduos")
    plt.xticks(range(tabela.shape[1]), tabela.columns, rotation=45, ha="right")
    plt.yticks(range(tabela.shape[0]), tabela.index)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(titulo)

    if tabela.shape[0] * tabela.shape[1] <= 250:
        for i in range(tabela.shape[0]):
            for j in range(tabela.shape[1]):
                valor = tabela.values[i, j]
                if valor != 0:
                    plt.text(j, i, str(valor), ha="center", va="center", fontsize=7)

    plt.tight_layout()
    path = os.path.join(output_dir, filename)
    plt.savefig(path, dpi=300)
    plt.show()

    return path


def plot_3d_comunidades(df_com, G, output_dir, prefix, titulo, max_edges_plot=15000):
    df_plot = df_com.copy()

    edges = list(G.edges())
    if len(edges) > max_edges_plot:
        rng = np.random.default_rng(RANDOM_STATE)
        idx = rng.choice(len(edges), size=max_edges_plot, replace=False)
        edges_plot = [edges[i] for i in idx]
    else:
        edges_plot = edges

    edge_x, edge_y, edge_z = [], [], []

    for u, v in edges_plot:
        x0, y0, z0 = G.nodes[u]["x"], G.nodes[u]["y"], G.nodes[u]["z"]
        x1, y1, z1 = G.nodes[v]["x"], G.nodes[v]["y"], G.nodes[v]["z"]

        edge_x += [x0, x1, None]
        edge_y += [y0, y1, None]
        edge_z += [z0, z1, None]

    edge_trace = go.Scatter3d(
        x=edge_x,
        y=edge_y,
        z=edge_z,
        mode="lines",
        line=dict(width=1, color="rgba(120,120,120,0.25)"),
        hoverinfo="none",
        showlegend=False
    )

    hover = (
        "Nó: " + df_plot["node_id"].astype(str) +
        "<br>Cadeia: " + df_plot["chain_id"].astype(str) +
        "<br>Resíduo: " + df_plot["residue_name"].astype(str) + " " + df_plot["residue_number"].astype(str) +
        "<br>Comunidade: " + df_plot["community"].astype(str)
    )

    node_trace = go.Scatter3d(
        x=df_plot["x"],
        y=df_plot["y"],
        z=df_plot["z"],
        mode="markers",
        marker=dict(
            size=3.5,
            color=df_plot["community"],
            colorscale="Viridis",
            opacity=0.85,
            showscale=True,
            colorbar=dict(title="Comunidade")
        ),
        hovertext=hover,
        hoverinfo="text",
        showlegend=False
    )

    fig = go.Figure(data=[edge_trace, node_trace])

    fig.update_layout(
        title=titulo,
        scene=dict(
            xaxis_title="X",
            yaxis_title="Y",
            zaxis_title="Z"
        ),
        width=950,
        height=750,
        margin=dict(l=0, r=0, b=0, t=40)
    )

    html_path = os.path.join(output_dir, f"{prefix}_3d_comunidades.html")
    fig.write_html(html_path)

    try:
        png_path = os.path.join(output_dir, f"{prefix}_3d_comunidades.png")
        fig.write_image(png_path, scale=2)
        print("Figura 3D PNG salva em:", png_path)
    except Exception as e:
        png_path = None
        print("Não foi possível salvar PNG estático da figura 3D. HTML salvo normalmente.")
        print("Motivo:", e)

    fig.show()
    print("Figura 3D HTML salva em:", html_path)

    return html_path, png_path


def exportar_resumo_txt(output_dir, filename, linhas):
    path = os.path.join(output_dir, filename)

    with open(path, "w", encoding="utf-8") as f:
        for linha in linhas:
            f.write(str(linha) + "\n")

    print("Resumo salvo em:", path)

    return path

"""# PARTE I — Proteína de teste 1A3N

A proteína 1A3N é utilizada como teste do pipeline antes da execução da proteína-alvo 6B1T. Ela é maior e estruturalmente mais interessante do que a 1CRN, mas ainda pequena o suficiente para permitir execução rápida.

# 5. Obtenção e preparação da proteína 1A3N
"""

PDB_TESTE = "1A3N"
limpar_diretorio(DIR_TESTE)

pdb_1a3n = baixar_pdb(PDB_TESTE, DIR_TESTE)

"""# 6. Leitura, parsing e extração dos resíduos da 1A3N"""

df_1a3n = carregar_residuos_ca(pdb_1a3n, PDB_TESTE)

df_1a3n.to_csv(
    os.path.join(DIR_TESTE, "1A3N_residuos_ca.csv"),
    index=False,
    encoding="utf-8-sig"
)

print("Número de resíduos carregados:", len(df_1a3n))
display(df_1a3n.head())

print()
print("Contagem por cadeia:")
display(df_1a3n["chain_id"].value_counts().sort_index())

"""# 7. Construção da rede da 1A3N"""

G_1a3n = construir_rede_por_distancia(df_1a3n, DISTANCE_THRESHOLD)

print("Nós:", G_1a3n.number_of_nodes())
print("Arestas:", G_1a3n.number_of_edges())

# Exporta arestas
pd.DataFrame([(u, v, d["distance"]) for u, v, d in G_1a3n.edges(data=True)], columns=["source", "target", "distance"]).to_csv(
    os.path.join(DIR_TESTE, "1A3N_arestas.csv"), index=False, encoding="utf-8-sig"
)

metricas_1a3n = salvar_metricas_rede(G_1a3n, DIR_TESTE, "1A3N")

"""# 8. Distribuição de graus da 1A3N"""

freq_1a3n, _, _ = plot_distribuicao_graus(
    G_1a3n,
    DIR_TESTE,
    "1A3N",
    "Distribuição de graus — proteína 1A3N"
)

"""# 9. Centralidades da 1A3N"""

df_cent_1a3n = calcular_centralidades(
    G_1a3n,
    DIR_TESTE,
    "1A3N",
    betweenness_k=BETWEENNESS_K_TESTE
)

plot_histogramas_centralidades(
    df_cent_1a3n,
    DIR_TESTE,
    "1A3N",
    "Distribuições das centralidades — 1A3N"
)

"""# 10. Louvain na 1A3N e validação por cadeia"""

partition_1a3n, modularidade_1a3n, num_com_1a3n, df_com_1a3n, resumo_com_1a3n = detectar_comunidades_louvain(
    G_1a3n,
    DIR_TESTE,
    "1A3N",
    resolution=LOUVAIN_RESOLUTION_TESTE
)

# Validação simples: comunidade × cadeia
ct_1a3n = pd.crosstab(df_com_1a3n["community"], df_com_1a3n["chain_id"])
ct_1a3n.to_csv(os.path.join(DIR_TESTE, "1A3N_comunidade_x_cadeia.csv"), encoding="utf-8-sig")

display(ct_1a3n)
plot_heatmap_crosstab(
    ct_1a3n,
    DIR_TESTE,
    "1A3N_heatmap_comunidade_x_cadeia.png",
    "1A3N — Comunidade × cadeia",
    "Cadeia",
    "Comunidade"
)

ari_1a3n = adjusted_rand_score(df_com_1a3n["chain_id"], df_com_1a3n["community"])
nmi_1a3n = normalized_mutual_info_score(df_com_1a3n["chain_id"], df_com_1a3n["community"])

metricas_valid_1a3n = pd.DataFrame({
    "Métrica": ["Modularidade", "ARI comunidade × cadeia", "NMI comunidade × cadeia"],
    "Valor": [modularidade_1a3n, ari_1a3n, nmi_1a3n]
})
metricas_valid_1a3n.to_csv(os.path.join(DIR_TESTE, "1A3N_metricas_validacao.csv"), index=False, encoding="utf-8-sig")
display(metricas_valid_1a3n.round(4))

"""# 11. Visualização 3D da 1A3N"""

plot_3d_comunidades(
    df_com_1a3n,
    G_1a3n,
    DIR_TESTE,
    "1A3N",
    "Visualização 3D da proteína 1A3N com comunidades Louvain",
    max_edges_plot=20000
)

"""# 12. Exportação final da 1A3N"""

exportar_resumo_txt(
    DIR_TESTE,
    "resumo_execucao_1A3N.txt",
    [
        "Projeto de Redes Complexas - Proteína de teste 1A3N",
        "="*70,
        f"Proteína: {PDB_TESTE}",
        f"Limiar de distância: {DISTANCE_THRESHOLD} Å",
        f"Nós: {G_1a3n.number_of_nodes()}",
        f"Arestas: {G_1a3n.number_of_edges()}",
        f"Comunidades Louvain: {num_com_1a3n}",
        f"Modularidade: {modularidade_1a3n:.4f}",
        f"ARI comunidade × cadeia: {ari_1a3n:.4f}",
        f"NMI comunidade × cadeia: {nmi_1a3n:.4f}",
        "",
        "Arquivos exportados:",
        *sorted(os.listdir(DIR_TESTE))
    ]
)

print("Arquivos exportados para:", DIR_TESTE)
for f in sorted(os.listdir(DIR_TESTE)):
    print("-", f)

"""# PARTE II — Proteína-alvo 6B1T

A proteína 6B1T é o alvo principal do projeto. Como o arquivo completo é disponibilizado pelo RCSB em pacote `tar.gz`, a execução utiliza os dois arquivos PDB extraídos do bundle:

- `6b1t-pdb-bundle1.pdb`
- `6b1t-pdb-bundle2.pdb`

A célula seguinte limpa arquivos anteriores e solicita o upload desses dois arquivos.

# 13. Preparação e upload dos arquivos da 6B1T
"""

from google.colab import files

PDB_6B1T = "6B1T"
EXTRACT_DIR_6B1T = "6b1t_extraido"

limpar_diretorio(DIR_6B1T)

# Remove arquivos antigos da raiz do Colab
for arquivo in glob.glob("6b1t*"):
    if os.path.isfile(arquivo):
        os.remove(arquivo)
    elif os.path.isdir(arquivo):
        shutil.rmtree(arquivo)

if os.path.exists(EXTRACT_DIR_6B1T):
    shutil.rmtree(EXTRACT_DIR_6B1T)
os.makedirs(EXTRACT_DIR_6B1T, exist_ok=True)

print("Faça upload APENAS destes dois arquivos:")
print("- 6b1t-pdb-bundle1.pdb")
print("- 6b1t-pdb-bundle2.pdb")

uploaded = files.upload()

for nome in uploaded.keys():
    destino = os.path.join(EXTRACT_DIR_6B1T, os.path.basename(nome))
    shutil.copy(nome, destino)

pdb_files_6b1t = sorted(glob.glob(os.path.join(EXTRACT_DIR_6B1T, "*.pdb")))

print()
print("Arquivos PDB encontrados:")
for f in pdb_files_6b1t:
    print("-", Path(f).name)

if len(pdb_files_6b1t) != 2:
    raise ValueError(f"Foram encontrados {len(pdb_files_6b1t)} arquivos PDB. O esperado é exatamente 2.")

"""# 14. Leitura, parsing e extração dos resíduos da 6B1T"""

df_6b1t = carregar_residuos_ca(pdb_files_6b1t, PDB_6B1T, max_residues=None)
df_6b1t.to_csv(os.path.join(DIR_6B1T, "6B1T_residuos_ca.csv"), index=False, encoding="utf-8-sig")

print("Número de resíduos carregados:", len(df_6b1t))
display(df_6b1t.head())
print()
print("Contagem por cadeia:")
display(df_6b1t["chain_id"].value_counts().sort_index())

"""# 15. Construção da rede da 6B1T"""

G_6b1t = construir_rede_por_distancia(df_6b1t, DISTANCE_THRESHOLD)

print("Nós:", G_6b1t.number_of_nodes())
print("Arestas:", G_6b1t.number_of_edges())

pd.DataFrame([(u, v, d["distance"]) for u, v, d in G_6b1t.edges(data=True)], columns=["source", "target", "distance"]).to_csv(
    os.path.join(DIR_6B1T, "6B1T_arestas.csv"), index=False, encoding="utf-8-sig"
)

metricas_6b1t = salvar_metricas_rede(G_6b1t, DIR_6B1T, "6B1T")

"""# 16. Distribuição de graus da 6B1T"""

freq_6b1t, _, _ = plot_distribuicao_graus(
    G_6b1t,
    DIR_6B1T,
    "6B1T",
    "Distribuição de graus — proteína 6B1T"
)

"""# 17. Centralidades da 6B1T

A Betweenness é calculada de forma aproximada para reduzir o custo computacional.
"""

df_cent_6b1t = calcular_centralidades(
    G_6b1t,
    DIR_6B1T,
    "6B1T",
    betweenness_k=BETWEENNESS_K_6B1T
)

plot_histogramas_centralidades(
    df_cent_6b1t,
    DIR_6B1T,
    "6B1T",
    "Distribuições das centralidades — 6B1T"
)

"""# 18. Louvain na 6B1T"""

partition_6b1t, modularidade_6b1t, num_com_6b1t, df_com_6b1t, resumo_com_6b1t = detectar_comunidades_louvain(
    G_6b1t,
    DIR_6B1T,
    "6B1T",
    resolution=LOUVAIN_RESOLUTION_6B1T
)

"""# 19. Comunidade × cadeia da 6B1T"""

ct_cadeia_6b1t = pd.crosstab(df_com_6b1t["community"], df_com_6b1t["chain_id"])
ct_cadeia_6b1t.to_csv(os.path.join(DIR_6B1T, "6B1T_comunidade_x_cadeia.csv"), encoding="utf-8-sig")

display(ct_cadeia_6b1t)
plot_heatmap_crosstab(
    ct_cadeia_6b1t,
    DIR_6B1T,
    "6B1T_heatmap_comunidade_x_cadeia.png",
    "6B1T — Comunidade × cadeia",
    "Cadeia",
    "Comunidade"
)

# ============================================================
# Heatmap: Comunidade × Família estrutural RCSB
# ============================================================

# Mapeamento das cadeias da 6B1T para as famílias estruturais
mapa_familias_6b1t = {
    # Hexon protein
    "A": "Hexon protein", "B": "Hexon protein", "C": "Hexon protein",
    "D": "Hexon protein", "E": "Hexon protein", "F": "Hexon protein",
    "G": "Hexon protein", "H": "Hexon protein", "I": "Hexon protein",
    "J": "Hexon protein", "K": "Hexon protein", "L": "Hexon protein",

    # Penton protein
    "M": "Penton protein",

    # Demais proteínas estruturais
    "N": "Pre-hexon-linking protein IIIa",
    "O": "Pre-hexon-linking protein IIIa",
    "P": "Pre-hexon-linking protein VIII",
    "Q": "Pre-hexon-linking protein VIII",
    "R": "Hexon-interlacing protein",
    "S": "Hexon-interlacing protein",
    "T": "Pre-protein VI",
    "U": "Pre-protein VI",
    "V": "Pre-histone-like nucleoprotein",
    "W": "Pre-histone-like nucleoprotein",
    "X": "Outras proteínas estruturais",
    "Y": "Outras proteínas estruturais"
}

df_com_6b1t["familia_rcsb"] = df_com_6b1t["chain_id"].map(mapa_familias_6b1t)

df_com_6b1t["familia_rcsb"] = df_com_6b1t["familia_rcsb"].fillna("Não mapeada")

tabela_comunidade_familia = pd.crosstab(
    df_com_6b1t["community"],
    df_com_6b1t["familia_rcsb"]
)

display(tabela_comunidade_familia)

tabela_comunidade_familia.to_csv(
    os.path.join(DIR_6B1T, "6B1T_tabela_comunidade_familia_rcsb.csv"),
    encoding="utf-8-sig"
)

plot_heatmap_crosstab(
    tabela_comunidade_familia,
    DIR_6B1T,
    "6B1T_heatmap_comunidade_familia_rcsb.png",
    "6B1T — Comunidade × família estrutural RCSB",
    "Família estrutural RCSB",
    "Comunidade Louvain"
)

"""# 20. Mapeamento das famílias estruturais da 6B1T segundo as anotações do RCSB

O mapeamento abaixo segue as famílias estruturais utilizadas na validação biológica da estrutura 6B1T.
"""

def classificar_familia_6b1t(chain_id):
    if chain_id in list("ABCDEFGHIJKL"):
        return "Hexon protein"
    elif chain_id == "M":
        return "Penton protein"
    elif chain_id == "N":
        return "Pre-hexon-linking protein IIIa"
    elif chain_id in ["O", "P"]:
        return "Pre-hexon-linking protein VIII"
    elif chain_id in ["Q", "R", "S", "T"]:
        return "Hexon-interlacing protein"
    elif chain_id in ["U", "V", "X", "Y"]:
        return "Pre-protein VI"
    elif chain_id == "W":
        return "Pre-histone-like nucleoprotein"
    else:
        return "Não classificado"


def classificar_minimo_6b1t(chain_id):
    if chain_id in list("ABCDEFGHIJKL"):
        return "Hexon / capsídeo"
    elif chain_id == "M":
        return "Penton / base"
    else:
        return "Outras proteínas"


df_com_6b1t["familia_rcsb"] = df_com_6b1t["chain_id"].apply(classificar_familia_6b1t)
df_com_6b1t["grupo_minimo"] = df_com_6b1t["chain_id"].apply(classificar_minimo_6b1t)

df_com_6b1t.to_csv(os.path.join(DIR_6B1T, "6B1T_comunidades_com_familias.csv"), index=False, encoding="utf-8-sig")

familias_6b1t = df_com_6b1t["familia_rcsb"].value_counts().reset_index()
familias_6b1t.columns = ["familia_rcsb", "quantidade_residuos"]
familias_6b1t.to_csv(os.path.join(DIR_6B1T, "6B1T_contagem_familias_rcsb.csv"), index=False, encoding="utf-8-sig")

display(familias_6b1t)

"""# 21. Validação biológica: Comunidade × Família"""

tabela_familia_6b1t = pd.crosstab(df_com_6b1t["community"], df_com_6b1t["familia_rcsb"])
tabela_familia_6b1t.to_csv(os.path.join(DIR_6B1T, "6B1T_comunidade_x_familia_rcsb.csv"), encoding="utf-8-sig")

display(tabela_familia_6b1t)
plot_heatmap_crosstab(
    tabela_familia_6b1t,
    DIR_6B1T,
    "6B1T_heatmap_comunidade_x_familia_rcsb.png",
    "6B1T — Comunidade × família estrutural RCSB",
    "Família estrutural",
    "Comunidade"
)

"""# 22. Validação mínima: Hexon × Penton"""

tabela_minima_6b1t = pd.crosstab(df_com_6b1t["community"], df_com_6b1t["grupo_minimo"])
tabela_minima_6b1t.to_csv(os.path.join(DIR_6B1T, "6B1T_comunidade_x_hexon_penton.csv"), encoding="utf-8-sig")

display(tabela_minima_6b1t)
plot_heatmap_crosstab(
    tabela_minima_6b1t,
    DIR_6B1T,
    "6B1T_heatmap_comunidade_x_hexon_penton.png",
    "6B1T — Comunidade × Hexon/Penton",
    "Grupo mínimo",
    "Comunidade"
)

"""# 23. Métricas quantitativas da validação biológica

As métricas abaixo comparam a partição encontrada pelo Louvain com as famílias estruturais anotadas.
"""

true_labels_familia = df_com_6b1t["familia_rcsb"]
pred_labels = df_com_6b1t["community"]

# Purity
ct = pd.crosstab(pred_labels, true_labels_familia)
purity_6b1t = ct.max(axis=1).sum() / ct.values.sum()

ari_6b1t = adjusted_rand_score(true_labels_familia, pred_labels)
nmi_6b1t = normalized_mutual_info_score(true_labels_familia, pred_labels)
hom_6b1t = homogeneity_score(true_labels_familia, pred_labels)
comp_6b1t = completeness_score(true_labels_familia, pred_labels)

metricas_valid_6b1t = pd.DataFrame({
    "Métrica": [
        "Modularidade",
        "Purity",
        "Adjusted Rand Index (ARI)",
        "Normalized Mutual Information (NMI)",
        "Homogeneity",
        "Completeness"
    ],
    "Valor": [
        modularidade_6b1t,
        purity_6b1t,
        ari_6b1t,
        nmi_6b1t,
        hom_6b1t,
        comp_6b1t
    ]
})

metricas_valid_6b1t.to_csv(os.path.join(DIR_6B1T, "6B1T_metricas_validacao_biologica.csv"), index=False, encoding="utf-8-sig")
display(metricas_valid_6b1t.round(4))

"""# 24. Visualização 3D da 6B1T com comunidades Louvain"""

plot_3d_comunidades(
    df_com_6b1t,
    G_6b1t,
    DIR_6B1T,
    "6B1T",
    "Visualização 3D da proteína 6B1T com comunidades Louvain",
    max_edges_plot=20000
)

"""# 25. Exportação final da 6B1T"""

exportar_resumo_txt(
    DIR_6B1T,
    "resumo_execucao_6B1T.txt",
    [
        "Projeto de Redes Complexas - Proteína-alvo 6B1T",
        "="*70,
        f"Proteína: {PDB_6B1T}",
        f"Arquivos PDB: {', '.join([Path(p).name for p in pdb_files_6b1t])}",
        f"Limiar de distância: {DISTANCE_THRESHOLD} Å",
        f"Nós: {G_6b1t.number_of_nodes()}",
        f"Arestas: {G_6b1t.number_of_edges()}",
        f"Comunidades Louvain: {num_com_6b1t}",
        f"Modularidade: {modularidade_6b1t:.4f}",
        f"Purity: {purity_6b1t:.4f}",
        f"ARI: {ari_6b1t:.4f}",
        f"NMI: {nmi_6b1t:.4f}",
        f"Homogeneity: {hom_6b1t:.4f}",
        f"Completeness: {comp_6b1t:.4f}",
        "",
        "Arquivos exportados:",
        *sorted(os.listdir(DIR_6B1T))
    ]
)

print("Arquivos exportados para:", DIR_6B1T)
for f in sorted(os.listdir(DIR_6B1T)):
    print("-", f)

"""# 26. Compactação dos resultados

A célula abaixo cria um arquivo `.zip` contendo todos os resultados exportados das duas proteínas.
"""

zip_name = "resultados_redes_complexas_1A3N_6B1T"
shutil.make_archive(zip_name, "zip", BASE_OUTPUT_DIR)
print("Arquivo compactado gerado:", zip_name + ".zip")

try:
    files.download(zip_name + ".zip")
except Exception:
    print("Download automático disponível apenas no Google Colab.")

"""# 27. Síntese final

Ao final da execução, o notebook terá produzido as saídas principais para o relatório:

- validação do pipeline na proteína 1A3N;
- execução completa da proteína-alvo 6B1T;
- distribuição de graus em histograma e escala log-log;
- centralidades e top 20 resíduos por métrica;
- comunidades detectadas pelo Louvain;
- tabelas de correspondência entre comunidades, cadeias e famílias estruturais;
- heatmaps de validação;
- métricas quantitativas de validação biológica;
- visualizações 3D interativas.
"""